### ISSUE TITLE
Blocked by CORS

### ISSUE THREAD

**Issue by sunnyguan** [itsjafer/resume-parser#4]
The AWS endpoint recently started having issues with CORS and can't return the parsed results; not sure if this is due to Lever's API or the AWS Lambda. 

`Access to fetch at 'https://g5wkkduchj.execute-api.us-east-2.amazonaws.com/Prod' from origin 'https://itsjafer.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Tested on Edge/Chrome/Safari with and without incognito.

**Comment by thesauravkarmakar** [comment]
> The AWS endpoint recently started having issues with CORS and can't return the parsed results; not sure if this is due to Lever's API or the AWS Lambda.
> 
> `Access to fetch at 'https://g5wkkduchj.execute-api.us-east-2.amazonaws.com/Prod' from origin 'https://itsjafer.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
> 
> Tested on Edge/Chrome/Safari with and without incognito.

Same issue on Brave with and without incognito.

**Comment by doitmaan** [comment]
same

**Comment by itsjafer** [comment]
Unfortunately this is an opaque error. The actual cause of the error is that the Lever API has restricted public access. I'm leaving this issue open until the Lever API is worked around

**Comment by itsjafer** [comment]
Update, it turns out a simple header spoof was enough to get this working again!
