### ISSUE TITLE
Parser fails to display text if no phone number provided

### ISSUE THREAD

**Issue by rajpiskala** [itsjafer/resume-parser#5]
If a resume does not have a phone number, no error or text is displayed to the screen.

The console has an error saying that `e.phones[0]` is undefined. I believe this is because the response data returns an empty array and it's trying to access the first element. I can't find the source code for the front end, but I believe this can be easily remedied by adding a null check to return "None" for phone number if it can't find any.

**Steps to replicate:**
Submit any resume without a phone number. You can remove the phone number from your resume to test this.

**Screenshot:**
![image](https://user-images.githubusercontent.com/57082175/131238839-35230a72-9ddf-4251-83ef-ac8b1bfb9aeb.png)

Analyzing the network response (not shown as it contains personal details) shows that the response data has phones as an empty array.

**Comment by itsjafer** [comment]
Thanks! I’ve updated the front end to handle this; I need to do a bit of a rewrite to display all the response info in a cleaner way.
